Revert pathing changes to API Ingress
Flagsmith/flagsmith-charts pull request #143
Opened 2023-07-21 13:33 UTC by ncalibey

PR #139 correctly fixed a pathing issue for the front-end ingress, but also made the same changes to the API server ingress in order to maintain consistency between the two. However, changing the ingress in the latter case was unnecessary and broke deployments that used specialized paths for the API server (e.g. using rewrites). This PR reverts the changes for the API server ingress and leaves the changes to the front-end ingress untouched.

Thanks for submitting a PR! Please check the boxes below:

- [x] I have filled in the "Changes" section below?
- [ ] I have filled in the "How did you test this code" section below?
- [x] I have bumped the version number in `/charts/flagsmith/Chart.yaml` in the section `version` or I'm merging to a
      release branch

## Changes

- Reverted changes to the API server ingress

## How did you test this code?

_Please describe._

2023-07-21 13:33 UTC, ncalibey commented
Note, if accepted, this will close #142

2023-07-21 13:34 UTC, ncalibey commented
Oops, seems some stuff from JetBrains got in there. I'll remove those from the PR

2023-07-24 13:27 UTC, khvn26 requested changes

2023-07-24 13:27 UTC, khvn26 commented on charts/flagsmith/templates/ingress-api.yaml
>                servicePort: {{ $svcPort }}
Had to move some lines around to make this work:

```suggestion
            {{- else }}
            backend:
              serviceName: {{ $fullName }}-api
              servicePort: {{ $svcPort }}
            {{- end }}
          {{- end }}
```

2023-07-24 13:38 UTC, khvn26 approved these changes

2023-07-24 13:38 UTC, merged